table Measure
	lineageTag: 97de4db7-de36-4438-b9f4-f62ce16565e8

	/// Migriert aus Qlik: Sum({<MASTER_CAL.Date 2025, AccountLevel1='GuV', AccountLevel2='Operatives Ergebnis', DataLevelName='Plan'>} FACTS.Value)
	measure 'GuV Plan Operatives Ergebnis' =
			CALCULATE(
			    SUM(Facts[Value]),
			    AccountStructure[AccountLevel1] = "GuV",
			    AccountStructure[AccountLevel2] = "Operatives Ergebnis",
			    DataLevel[DataLevelName] = "Plan"
			)
		formatString: #,##0.00
		displayFolder: Standard
		lineageTag: 652b6aed-d585-485d-8f81-bc4fb675d95f

	measure 'GuV Ist Operatives Ergebnis' =
			CALCULATE(
			    SUM(Facts[Value]),
			    AccountStructure[AccountLevel1] = "GuV",
			    AccountStructure[AccountLevel2] = "Operatives Ergebnis",
			    DataLevel[DataLevelName] = "Ist"
			)
		formatString: 0
		displayFolder: Standard
		lineageTag: a1155a90-c605-46b3-a5f7-cfb7f27c1907

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'GuV Ist' =
			CALCULATE(
			    SUM(Facts[Value]),
			    AccountStructure[AccountLevel1] = "GuV",
			    DataLevel[DataLevelName] = "Ist"
			)
		displayFolder: Standard
		lineageTag: 1ecbb5d2-fa92-4044-98c1-ef13a370f779

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GuV Ist ACT' = CALCULATE([GuV Ist])
		displayFolder: Time Intelligence\01 Current Period
		lineageTag: 1c5f1136-8a33-424a-8993-95e0cf40a6a8

	measure 'GuV Ist LY' = CALCULATE([GuV Ist], SAMEPERIODLASTYEAR('Datum'[Datum]))
		displayFolder: Time Intelligence\02 Last Year
		lineageTag: 518adbaa-1ca0-4a8b-96fb-d8cb762989e4

	measure 'GuV Ist Delta' = [GuV Ist ACT] - [GuV Ist LY]
		displayFolder: Time Intelligence\03 YoY Variance (Monthly)
		lineageTag: 54e4924e-4b30-4d4e-9dd8-74f206ae9d2b

	measure 'GuV Ist Delta %' = DIVIDE([GuV Ist Delta], [GuV Ist LY])
		formatString: 0.00%
		displayFolder: Time Intelligence\03 YoY Variance (Monthly)
		lineageTag: db0b1c6f-c762-4b8f-920f-d7667a001795

	measure 'GuV Ist YTD' =
			
			CALCULATE(
			    [GuV Ist],
			    DATESYTD('Datum'[Datum]),
			    'Datum'[Datum] <= TODAY(),
			    REMOVEFILTERS('Datum'[Jahr])
			)
		displayFolder: Time Intelligence\04 YTD
		lineageTag: aa401cc9-6487-4b8a-9d01-bd7926584c04

	measure 'GuV Ist LYTD' =
			
			CALCULATE(
			    [GuV Ist],
			    FILTER(
			        SAMEPERIODLASTYEAR(DATESYTD('Datum'[Datum])),
			        'Datum'[Datum] <= EDATE(TODAY(), -12)
			    ),
			    REMOVEFILTERS('Datum'[Jahr])
			)
		displayFolder: Time Intelligence\05 LYTD
		lineageTag: ad6da810-fc34-4032-8705-7ddf884e3a38

	measure 'GuV Ist YTD Total' =
			VAR _Heute = TODAY()
			VAR _ZeilenDatum = MAX('Datum'[Datum])
			RETURN IF(_ZeilenDatum <= _Heute, [GuV Ist YTD], BLANK())
		displayFolder: Time Intelligence\06 YTD Total
		lineageTag: 33d60c05-4bc2-4659-85c7-6d82263dc421

	measure 'GuV Ist LYTD Total' =
			VAR _Heute = TODAY()
			VAR _ZeilenDatum = MAX('Datum'[Datum])
			RETURN IF(_ZeilenDatum <= _Heute, [GuV Ist LYTD], BLANK())
		displayFolder: Time Intelligence\06 YTD Total
		lineageTag: 1330c32d-e4ad-48f1-a39b-8b443443be99

	measure 'GuV Ist YoY Total' = [GuV Ist YTD Total] - [GuV Ist LYTD Total]
		displayFolder: Time Intelligence\07 YoY Variance (YTD)
		lineageTag: 7214a1dc-d31f-4143-a881-a21e31152582

	measure 'GuV Ist YoY Total %' = DIVIDE([GuV Ist YoY Total], [GuV Ist LYTD Total])
		formatString: 0.00%
		displayFolder: Time Intelligence\07 YoY Variance (YTD)
		lineageTag: a4840d18-3e7e-4f7d-8fe8-5ea6a4ba2431

	measure 'GuV Plan' =
			CALCULATE(
			    SUM(Facts[Value]),
			    AccountStructure[AccountLevel1] = "GuV",
			    DataLevel[DataLevelName] = "Plan"
			)
		displayFolder: Standard
		lineageTag: 5920f868-eaaa-4c20-abd1-dd115385a63b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GuV Plan ACT' = CALCULATE([GuV Plan])
		displayFolder: Time Intelligence\01 Current Period
		lineageTag: 6afade58-4736-4c98-9da8-6256efad775b

	measure 'GuV Plan LY' = CALCULATE([GuV Plan], SAMEPERIODLASTYEAR('Datum'[Datum]))
		displayFolder: Time Intelligence\02 Last Year
		lineageTag: 66f4bcbe-ad74-4395-b58b-c3346e214b81

	measure 'GuV Plan Delta' = [GuV Plan ACT] - [GuV Plan LY]
		displayFolder: Time Intelligence\03 YoY Variance (Monthly)
		lineageTag: 0eab18c9-c5e8-43b0-b244-ac9996224b06

	measure 'GuV Plan Delta %' = DIVIDE([GuV Plan Delta], [GuV Plan LY])
		formatString: 0.00%
		displayFolder: Time Intelligence\03 YoY Variance (Monthly)
		lineageTag: 86396a69-0d8c-4d49-a542-4296613640a0

	measure 'GuV Plan YTD' =
			
			CALCULATE(
			    [GuV Plan],
			    DATESYTD('Datum'[Datum]),
			    'Datum'[Datum] <= TODAY(),
			    REMOVEFILTERS('Datum'[Jahr])
			)
		displayFolder: Time Intelligence\04 YTD
		lineageTag: 1b0aa7c7-2147-4b7a-97d0-4fc1f1660308

	measure 'GuV Plan LYTD' =
			
			CALCULATE(
			    [GuV Plan],
			    FILTER(
			        SAMEPERIODLASTYEAR(DATESYTD('Datum'[Datum])),
			        'Datum'[Datum] <= EDATE(TODAY(), -12)
			    ),
			    REMOVEFILTERS('Datum'[Jahr])
			)
		displayFolder: Time Intelligence\05 LYTD
		lineageTag: 3f50bec7-15a5-409c-90d8-a46febb1a8fb

	measure 'GuV Plan YTD Total' =
			VAR _Heute = TODAY()
			VAR _ZeilenDatum = MAX('Datum'[Datum])
			RETURN IF(_ZeilenDatum <= _Heute, [GuV Plan YTD], BLANK())
		displayFolder: Time Intelligence\06 YTD Total
		lineageTag: f8606424-5988-44de-9947-d3d9ca1192d7

	measure 'GuV Plan LYTD Total' =
			VAR _Heute = TODAY()
			VAR _ZeilenDatum = MAX('Datum'[Datum])
			RETURN IF(_ZeilenDatum <= _Heute, [GuV Plan LYTD], BLANK())
		displayFolder: Time Intelligence\06 YTD Total
		lineageTag: 20cbcd26-49c7-4d50-a6cb-b3179ffbf597

	measure 'GuV Plan YoY Total' = [GuV Plan YTD Total] - [GuV Plan LYTD Total]
		displayFolder: Time Intelligence\07 YoY Variance (YTD)
		lineageTag: 11c0b71f-4564-4f83-ad89-b67560f0b5b0

	measure 'GuV Plan YoY Total %' = DIVIDE([GuV Plan YoY Total], [GuV Plan LYTD Total])
		formatString: 0.00%
		displayFolder: Time Intelligence\07 YoY Variance (YTD)
		lineageTag: 74f89e27-2533-4ab0-b70d-427827bc20c2

	measure 'GuV Ist Operatives Ergebnis ACT' = CALCULATE([GuV Ist Operatives Ergebnis])
		displayFolder: Time Intelligence\01 Current Period
		lineageTag: 8588099d-cd60-4a68-9405-0fe3a43bfbb8

	measure 'GuV Ist Operatives Ergebnis LY' = CALCULATE([GuV Ist Operatives Ergebnis], SAMEPERIODLASTYEAR('Datum'[Datum]))
		displayFolder: Time Intelligence\02 Last Year
		lineageTag: 27c1d823-dafe-4145-837c-9a7eea704a9e

	measure 'GuV Ist Operatives Ergebnis Delta' = [GuV Ist Operatives Ergebnis ACT] - [GuV Ist Operatives Ergebnis LY]
		displayFolder: Time Intelligence\03 YoY Variance (Monthly)
		lineageTag: dbe8e972-5eb0-4788-8746-e3c07b187b16

	measure 'GuV Ist Operatives Ergebnis Delta %' = DIVIDE([GuV Ist Operatives Ergebnis Delta], [GuV Ist Operatives Ergebnis LY])
		formatString: 0.00%
		displayFolder: Time Intelligence\03 YoY Variance (Monthly)
		lineageTag: b7074d83-0a9f-4142-aa4e-bf80364f84f2

	measure 'GuV Ist Operatives Ergebnis YTD' =
			
			CALCULATE(
			    [GuV Ist Operatives Ergebnis],
			    DATESYTD('Datum'[Datum]),
			    'Datum'[Datum] <= TODAY(),
			    REMOVEFILTERS('Datum'[Jahr])
			)
		displayFolder: Time Intelligence\04 YTD
		lineageTag: aeb386a4-6be1-4baa-aea4-d0dcbdad7b0c

	measure 'GuV Ist Operatives Ergebnis LYTD' =
			
			CALCULATE(
			    [GuV Ist Operatives Ergebnis],
			    FILTER(
			        SAMEPERIODLASTYEAR(DATESYTD('Datum'[Datum])),
			        'Datum'[Datum] <= EDATE(TODAY(), -12)
			    ),
			    REMOVEFILTERS('Datum'[Jahr])
			)
		displayFolder: Time Intelligence\05 LYTD
		lineageTag: 2f92b080-b2f5-49ef-bee8-1905a92b79f3

	measure 'GuV Ist Operatives Ergebnis YTD Total' =
			VAR _Heute = TODAY()
			VAR _ZeilenDatum = MAX('Datum'[Datum])
			RETURN IF(_ZeilenDatum <= _Heute, [GuV Ist Operatives Ergebnis YTD], BLANK())
		displayFolder: Time Intelligence\06 YTD Total
		lineageTag: 2ef13cbd-addb-449a-ad3d-6cdd0d626c52

	measure 'GuV Ist Operatives Ergebnis LYTD Total' =
			VAR _Heute = TODAY()
			VAR _ZeilenDatum = MAX('Datum'[Datum])
			RETURN IF(_ZeilenDatum <= _Heute, [GuV Ist Operatives Ergebnis LYTD], BLANK())
		displayFolder: Time Intelligence\06 YTD Total
		lineageTag: bfc28605-e3d1-41b3-acd8-f19143bd54f0

	measure 'GuV Ist Operatives Ergebnis YoY Total' = [GuV Ist Operatives Ergebnis YTD Total] - [GuV Ist Operatives Ergebnis LYTD Total]
		displayFolder: Time Intelligence\07 YoY Variance (YTD)
		lineageTag: ddb52f34-cf9a-44db-a69d-3bd94d7f0e11

	measure 'GuV Ist Operatives Ergebnis YoY Total %' = DIVIDE([GuV Ist Operatives Ergebnis YoY Total], [GuV Ist Operatives Ergebnis LYTD Total])
		formatString: 0.00%
		displayFolder: Time Intelligence\07 YoY Variance (YTD)
		lineageTag: 668931b7-429f-4edd-8339-24e8fccb8253

	measure 'GuV Plan Operatives Ergebnis ACT' = CALCULATE([GuV Plan Operatives Ergebnis])
		displayFolder: Time Intelligence\01 Current Period
		lineageTag: b97ac6ee-d760-4b80-ae5a-931fd0425b36

	measure 'GuV Plan Operatives Ergebnis LY' = CALCULATE([GuV Plan Operatives Ergebnis], SAMEPERIODLASTYEAR('Datum'[Datum]))
		displayFolder: Time Intelligence\02 Last Year
		lineageTag: 58b7182f-96b9-44ce-b703-ef650d7635c8

	measure 'GuV Plan Operatives Ergebnis Delta' = [GuV Plan Operatives Ergebnis ACT] - [GuV Plan Operatives Ergebnis LY]
		displayFolder: Time Intelligence\03 YoY Variance (Monthly)
		lineageTag: 0000ddc9-7f57-4852-be44-8560d489dafc

	measure 'GuV Plan Operatives Ergebnis Delta %' = DIVIDE([GuV Plan Operatives Ergebnis Delta], [GuV Plan Operatives Ergebnis LY])
		formatString: 0.00%
		displayFolder: Time Intelligence\03 YoY Variance (Monthly)
		lineageTag: 439e336f-17c2-42c8-9e72-0a1339567f48

	measure 'GuV Plan Operatives Ergebnis YTD' =
			
			CALCULATE(
			    [GuV Plan Operatives Ergebnis],
			    DATESYTD('Datum'[Datum]),
			    'Datum'[Datum] <= TODAY(),
			    REMOVEFILTERS('Datum'[Jahr])
			)
		displayFolder: Time Intelligence\04 YTD
		lineageTag: c00f20e7-03cf-42b2-9acb-0702bfb1afca

	measure 'GuV Plan Operatives Ergebnis LYTD' =
			
			CALCULATE(
			    [GuV Plan Operatives Ergebnis],
			    FILTER(
			        SAMEPERIODLASTYEAR(DATESYTD('Datum'[Datum])),
			        'Datum'[Datum] <= EDATE(TODAY(), -12)
			    ),
			    REMOVEFILTERS('Datum'[Jahr])
			)
		displayFolder: Time Intelligence\05 LYTD
		lineageTag: f736188f-3883-4be0-8bde-2b0d1f5ce549

	measure 'GuV Plan Operatives Ergebnis YTD Total' =
			VAR _Heute = TODAY()
			VAR _ZeilenDatum = MAX('Datum'[Datum])
			RETURN IF(_ZeilenDatum <= _Heute, [GuV Plan Operatives Ergebnis YTD], BLANK())
		displayFolder: Time Intelligence\06 YTD Total
		lineageTag: 55c0a3e0-48d3-4971-8394-4c858df65c37

	measure 'GuV Plan Operatives Ergebnis LYTD Total' =
			VAR _Heute = TODAY()
			VAR _ZeilenDatum = MAX('Datum'[Datum])
			RETURN IF(_ZeilenDatum <= _Heute, [GuV Plan Operatives Ergebnis LYTD], BLANK())
		displayFolder: Time Intelligence\06 YTD Total
		lineageTag: ef4dab03-fa49-4633-9ec6-a9b588908463

	measure 'GuV Plan Operatives Ergebnis YoY Total' = [GuV Plan Operatives Ergebnis YTD Total] - [GuV Plan Operatives Ergebnis LYTD Total]
		displayFolder: Time Intelligence\07 YoY Variance (YTD)
		lineageTag: ab4fb6a8-cd30-4124-a5ed-adfeb9abb87f

	measure 'GuV Plan Operatives Ergebnis YoY Total %' = DIVIDE([GuV Plan Operatives Ergebnis YoY Total], [GuV Plan Operatives Ergebnis LYTD Total])
		formatString: 0.00%
		displayFolder: Time Intelligence\07 YoY Variance (YTD)
		lineageTag: ff5552ce-c936-42b6-92bb-272d58e5e2f0

	measure 'GuV Ist Umsatzerlöse' =
			CALCULATE(
			    SUM(Facts[Value]),
			    AccountStructure[AccountLevel1] = "GuV",
			    AccountStructure[AccountLevel2] = "Umsatzerlöse",
			    DataLevel[DataLevelName] = "Ist"
			)
		displayFolder: Standard
		lineageTag: 6c0d1a43-e133-4e9c-b62e-1f5e4fd56729

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Date_Min =
			
			VAR _MinMonth = MIN('Datum'[Monat])
			RETURN
			FORMAT(DATE(2026, _MinMonth, 1), "MMMM")
		displayFolder: Standard
		lineageTag: 41542f3d-5c83-4a09-bd80-d65505ad0011

	measure Date_Max =
			
			VAR _MinMonth = MAX('Datum'[Monat])
			RETURN
			FORMAT(DATE(2026, _MinMonth, 1), "MMMM")
		displayFolder: Standard
		lineageTag: 256f7090-9ef3-407e-9ff7-afefbeacd057

	measure Max_Year = MAX(Datum[Jahr])
		formatString: 0
		displayFolder: Standard
		lineageTag: 59c5b7dc-cc13-450c-a198-d976ce9bf6fe

	column Measure
		dataType: string
		isHidden
		lineageTag: d741ebb0-0512-4bd7-b773-2141b3e8667f
		summarizeBy: none
		sourceColumn: Measure

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Measure = m
		mode: import
		source =
				let
				    Quelle = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WKi7IUIqNBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measure = _t]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(Quelle,{{"Measure", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

